server:
  port: 5001

spring:
  application:
    name: order-service
  profiles:
    active: dev
  cloud:
    stream:
      function:
        autodetect: true
      bindings:
        submitOrder-out-0:
          destination: submitOrder
          content-type: application/json

        orderStockRejected-in-0:
          destination: orderStockRejected
          content-type: application/json

      kafka:
        binder:
          auto-create-topics: true
          brokers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/