spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:3000"
              - "http://localhost:5000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: 
              - Content-Type
              - Accept
              - Authorization
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: actuator
          uri: lb://GATEWAY-SERVICE  
          predicates:
            - Path=/actuator/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/v1/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/api/v1/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG