server:
  port: 5003


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId},%X{spanId}] %-5level %logger{36} - %msg%n"

spring:
  application:
    name: product-service
  boot:
    admin:
      client:
        url: http://localhost:5050
        instance:
          service-url: http://localhost:5003
  cloud:
    stream:
      function:
        autodetect: true
      bindings:
        # Consumer
        submitOrder-in-0:
          destination: submitOrder
          content-type: application/json
        orderStockRejected-out-0:
          destination: orderStockRejected
          content-type: application/json
        orderStockConfirmed-out-0:
          destination: orderStockConfirmed
          content-type: application/json
      kafka:
        binder:
          auto-create-topics: true
          brokers: localhost:29092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


management:
  tracing:
    sampling:
      probability: 1.0  # Tüm request’leri trace et
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: ALWAYS


# http://localhost:9411/zipkin/
