server:
  port: 5003

spring:
  application:
    name: product-service

  cloud:
    stream:
      function:
        autodetect: true
      bindings:
        # Consumer
        submitOrder-in-0:
          destination: submitOrder
          content-type: application/json
        orderStockRejected-out-0:
          destination: orderStockRejected
          content-type: application/json
        orderStockConfirmed-out-0:
          destination: orderStockConfirmed
          content-type: application/json
      kafka:
        binder:
          auto-create-topics: true
          brokers: localhost:9092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true