

spring:
  application:
    name: saga-service
  cloud:
    function:
      definition: submitOrderConsumer,stockCheckConsumer,paymentConsumer
    stream:
      bindings:
        orderStateOut-out-0:
          destination: order-events
          content-type: application/json
        submitOrderConsumer-in-0:
          destination: order-events
          group: saga-group
        stockCheckConsumer-in-0:
          destination: order-events
          group: saga-group
        paymentConsumer-in-0:
          destination: order-events
          group: saga-group
      kafka:
        binder:
          auto-create-topics: true
          brokers: localhost:9092
